server:
  port: 9003
  servlet:
    context-path: /auth

spring:
  application:
    name: api-auth
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/auth?allowPublicKeyRetieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=America/Sao_Paulo
    username: root
    password: mysql
  jmx:
    enabled: false
  hateoas:
    use-hal-as-default-json-media-type: false

security:
  jwt:
    token:
      secret-key: rafhael-auth-ms
      expire-length: 360000
